baseurl: '/'
permalink: pretty
title: 'Collective Voices for Buildings in India'

logo:
  mobile: "images/logo/cvb-india.svg"
  mobile_height: "32px"
  mobile_width: "120px"
  desktop: "images/logo/cvb-india.svg"
  desktop_height: "48px"
  desktop_width: "180px"

home: 
  limit_services: 6
  limit_activities: 6

collections:
  services:
    output: true
    sort_by: weight
  activities:
    output: true
    sort_by: weight    
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "activities"
    values:
      layout: "activity"
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
